package com.yesgenie.pageobjects.enums;

public enum ProfilerEnum {


    INDIVIDUAL_CUSTOMER_NAME("Individual Customer Name"),
    PROFILER_HEADER_LABEL("Profiler Header Label"),
    PROFILER_HEADER_LABELMOBILE("Profiler Header Label Mobile"),
    INDIVIDUAL_PROSPECT_ID("Individual Prospect ID"),
    PRIMARY_DETAILS("PD Primary Details"),
    FAMILY_DETAILS("Family Details"),
    PROFESSIONAl_DETAILS("Professional Details"),
    FINANCIAL_PROFILE("Financial Profile"),
    OPPORTUNITIES("Opportunities"),
    LIFESTYLE("Lifestyle"),
    PD_MOBILE("PD Mobile"),
    PD_FIRST_NAME("PD First Name"),
    PD_LAST_NAME("PD Last Name"),
    PD_AGE("PD Age"),
    PD_RESIDENTIAL_ADDRESS_1("PD Residential Address 1"),
    PD_RESIDENTIAL_ADDRESS_2("PD Residential Address 2"),
    PD_RESIDENTIAL_CITY("PD Residential City"),
    PD_RESIDENTIAL_PINCODE("PD Residential Pincode"),
    PD_EMAIL_ID("PD Email ID"),
    PD_MALE("PD Male"),
    PD_FEMALE("PD Female"),
    PD_OTHERS("PD Others"),
    PD_EDIT("PD Edit"),
    PD_CANCEL("PD Cancel"),
    MOBILE_PD_AGE("Mobile PD Age"),
    MOBILE_PD_NAME("Mobile PD Name"),
    MOBILE_PD_PINCODE("Mobile PD Pincode"),
    FD_MARITAL_STATUS("FD Marital Status"),
    FD_NO_OF_CHILDREN("FD No. of Children"),
    FD_MARRIED("FD Married"),
    FD_SINGLE("FD Single"),
    FD_FAMILY_MEMBERS("FD Family Members"),
    FD_NAME("FD Name"),
    FD_OCCUPATION("FD Occupation"),
    FD_BANKING_WITH_YESBANK("FD Banking with Yesbank?"),
    FD_RELATIONSHIP("FD Relationship"),
    FD_EDIT("FD Edit"),
    FD_CANCEL("FD Cancel"),
    PRD_EMPLOYMENT_TYPE("PrD Employment Type"),
    PRD_TYPE_OF_COMPANYFIRM("PrD Type of Company/Firm"),
    PRD_TYPE_OF_COMPANYFIRM_OTHER("PrD Type of Company/Firm Other"),
    PRD_COMPANY_NAME("PrD Company Name"),
    PRD_INDUSTRY("PrD Industry"),
    PRD_INDUSTRY_OTHERS("PrD Industry others"),
    PRD_DESIGNATION("PrD Designation"),
    PRD_DEPARTMENT("PrD Department"),
    PRD_ANNUAL("PrD Annual"),
    PRD_SOURCE("PrD Source"),
    PRD_EDIT("PrD Edit"),
    PRDCANCEL("PrDCancel"),
    FP_FINANCIAL_PROFILE("FP Financial Profile"),
    FP_BANK_NAME("FP Bank Name"),
    FP_PRODUCT_HELD("FP Product Held"),
    FP_VALUE_OF_RELATIONSHIP("FP Value of Relationship"),
    FP_ADDITONAL_DETAILS("FP Additonal Details"),
    FP_ANNUAL_FAMILY_INCOME("FP Annual Family Income"),
    FP_ANNUAL_FAMILY_SAVING("FP Annual Family Saving"),
    FP_FINANCIAL_GOALS("FP Financial Goals"),
    FP_FINANCIAL_GOALS_OTHERS("FP Financial Goals Others"),
    FP_MOST_PREFERRED_INVESTMENTS("FP Most Preferred Investments"),
    FP_INVESTMENT_HORIZON("FP Investment Horizon"),
    FP_RISK_APPETITE("FP Risk Appetite"),
    FP_TOTAL_CLIENT_NETWORTH("FP Total Client Networth:"),
    FP_PROPERTY("FP Property"),
    FP_BANK_AC("FP Bank A/C"),
    FP_INSURANCE("FP Insurance"),
    FP_DIRECT("FP Direct"),
    //    FP_BANK_AC("FP Bank A/C"),
//    FP_INSURANCE("FP Insurance"),
//    FP_DIRECT("FP Direct"),
//    FP_BANK_AC("FP Bank A/C"),
    FP_EQUITY("FP Equity"),
    FP_DEBT("FP Debt"),
    FP_OTHERS("FP Others"),
    FP_EDIT("FD Edit"),
    FP_CANCEL("FD Cancel"),
    O_DEPOSITS("O Deposits"),
    O_INVESTMENTS("O Investments"),
    O_LOANS("O Loans"),
    O_CARDS_AND_WALLETS("O Cards and Wallets"),
    O_OTHERS("O Others"),
    O_EDIT("O Edit"),
    O_CANCEL("O Cancel"),
    L_NO_OF_CARS_OWNED("L No. of Cars Owned"),
    L_BRANDS_OF_CARS("L Brands of Cars"),
    L_PRIMARY_CREDIT_CARD("L Primary Credit Card"),
    L_HOME_TYPE("L Home Type"),
    L_MUSICAL_INTEREST("L Musical Interest"),
    L_HOME_PURCHASE_FUNDING("L Home Purchase Funding"),
    L_SPORTS_INTERESTS("L Sports Interests"),
    L_OTHER_HOBBIES("L Other Hobbies"),
    L_EDIT("L Edit"),
    L_CANCEL("L Cancel"),

    //NonIndividual Profiler
    NON_INDIVIDUAL_CUSTOMER_NAME("Non Individual Customer Name"),
    NON_INDIVIDUAL_PROSPECT_ID("Non Individual Prospect ID"),
    NPRIMARY_DETAILS("Primary Details"),
    CORPORATE_DETAILS("Corporate Details"),
    COMPETITION_HOLDING("Competition Holding"),
    ENGAGEMENT_HOOKS("Engagement Hooks"),
    ADDRESS_DETAILS("Address Details"),

    //Individual Family Edit
    FDRELATIONSHIPEDIT("FD Relationship Edit"),
    FDNAMEEDIT("FD NameEdit"),
    FDAGEEDIT("FD AgeEdit"),
    FDOCCUPATIONEDIT("FD OccupationEdit"),
    FDPRIMARYBANKEREDIT("FD PrimaryBankerEdit"),

    FPPRIMARYBANKEREDIT("FP Relationship Edit"),

    CHVALUEOFR("CH Value of Relationship"),
    BUILDINGNUMBER("Building Number Edit"),
    CITY("City Edit"),

    //Profiler All Label
    PDENITTYNAME("PD Entity Name"),
    PDCONTACTNAME("PD Contact Name"),
    PDCONTACTEMAIL("PD Contact Email"),
    PDPINCODE("PD Pin Code"),
    ADPERMANENTADDRESS("AD Permanent Address"),
    CDDATE("CD Date"),
    CHBANK1("CH Bank I"),
    FDENGAGEMENTHOOK("Engagement Hook Trade"),
    PDENTITYNAMEMOBILE("PD Entity Name Mobile"),
    NICDDATEMOBILE("CD Date Mobile"),
    NICHBANK("CH Bank I Mobile"),
    NIENGAGEMENTHOOKMOBILE("Engagement Hook Trade Mobile");




    public final String property;

    ProfilerEnum(String property) {
        this.property = property;
    }
}
